export const translations = {
  en: {
    nav: {
      pricing: 'Pricing',
      begin: 'Begin',
    },
    langToggle: 'ES',
    home: {
      eyebrow: 'A new kind of mirror',
      headlineL1: "You've been",
      headlineL2: 'everything',
      headlineL3: 'to everyone.',
      headlineEm: 'Who are you?',
      subL1: "An AI that doesn't fix you,",
      subL2: 'advise you, or optimize you.',
      subL3: 'It simply helps you find yourself.',
      begin: 'Begin',
      quote: '"The longest journey is the journey inward."',
      quoteAuthor: '— Dag Hammarskjöld',
      scroll: 'Scroll',
      whatLabel: 'What this is',
      whatH2L1: 'Not therapy.',
      whatH2L2: 'Not a chatbot.',
      whatH2Em: 'A witness.',
      whatP1: 'Most of us have never had a space to speak freely — without being judged, advised, or redirected. We perform for everyone, including ourselves.',
      whatP2: "whoiam.love is an AI that listens differently. It asks the questions no one else does. It remembers everything you've said. Over time, it holds a portrait of you that you've built word by word.",
      whatP3: 'Not a diagnosis. Not a score. A living record of who you are, becoming.',
      howLabel: 'How it works',
      howH2L1: 'The simplest thing.',
      howH2Em: 'A conversation.',
      steps: [
        { n: 'i.', title: 'You speak', body: "Start anywhere. A feeling, a fear, a memory. There's no wrong beginning. The AI meets you exactly where you are." },
        { n: 'ii.', title: 'It listens', body: 'No advice. No judgment. Just the kind of deep attention that helps you hear yourself more clearly.' },
        { n: 'iii.', title: 'You see yourself', body: "Patterns emerge. Contradictions surface. Every week, a portrait — assembled from your own words — of who you're becoming." },
      ],
      questionsLabel: 'The questions',
      questionsH2L1: 'The ones',
      questionsH2L2: 'no one',
      questionsH2Em: 'ever asks.',
      questions: [
        "What's something you've never said out loud?",
        'When did you stop being who you were meant to be?',
        "What do you want that you're ashamed to want?",
        'Who are you when no one is watching?',
        "What would you do if you weren't afraid?",
        "What does love feel like when it's yours?",
      ],
      ctaH2L1: 'Ready to meet',
      ctaH2Em: 'yourself?',
      ctaSub: 'Join the early access list. Be among the first to begin.',
      ctaPlaceholder: 'Your email',
      ctaBtn: 'Begin →',
      ctaNote: 'Free to start · No credit card · Just you',
      ctaConfirm: "You're on the list. The journey begins soon.",
      footerRights: '© 2026 · All rights reserved',
      footerMade: 'Made with love, powered by AI',
    },
    chat: {
      opening: "What's something you've never said out loud?",
      placeholder: 'Speak freely…',
      send: 'Send',
      hint: 'Enter to send · Shift + Enter for new line',
      error: 'Something interrupted the silence. Try again.',
    },
    pricing: {
      label: 'Pricing',
      headlineL1: 'Choose how deep',
      headlineEm: 'you want to go.',
      sub: "Start free. Go deeper when you're ready.",
      discover: {
        tier: 'Discover',
        price: 'Free',
        description: 'A space to speak. An AI that holds the silence with you, asks the question no one else does.',
        features: ['Unlimited conversations', 'AI that listens deeply', 'One question at a time', 'No memory between sessions'],
        cta: 'Begin Discovering',
      },
      experience: {
        badge: 'Coming soon',
        tier: 'Experience',
        description: 'The AI begins to know you. Patterns surface. A portrait emerges — assembled, over time, from your own words.',
        features: ['Everything in Discover', 'Memory across all sessions', 'AI notices patterns over time', 'Weekly self-portrait', 'Priority access to new features'],
        cta: 'Join the Waitlist',
      },
    },
    enter: {
      label: 'Private access',
      headlineL1: 'This space is',
      headlineEm: 'by invitation.',
      sub: 'Enter your invite code to begin.',
      placeholder: 'Invite code',
      cta: 'Enter',
      error: "That code isn't right. Try again.",
    },
  },

  es: {
    nav: {
      pricing: 'Precios',
      begin: 'Comenzar',
    },
    langToggle: 'EN',
    home: {
      eyebrow: 'Un nuevo tipo de espejo',
      headlineL1: 'Has sido',
      headlineL2: 'todo',
      headlineL3: 'para todos.',
      headlineEm: '¿Quién eres?',
      subL1: 'Una IA que no te arregla,',
      subL2: 'aconseja ni optimiza.',
      subL3: 'Simplemente te ayuda a encontrarte.',
      begin: 'Comenzar',
      quote: '"El viaje más largo es el viaje hacia adentro."',
      quoteAuthor: '— Dag Hammarskjöld',
      scroll: 'Bajar',
      whatLabel: 'Qué es esto',
      whatH2L1: 'No es terapia.',
      whatH2L2: 'No es un chatbot.',
      whatH2Em: 'Es un testigo.',
      whatP1: 'La mayoría nunca ha tenido un espacio para hablar libremente — sin ser juzgado, aconsejado ni redirigido. Actuamos para todos, incluso para nosotros mismos.',
      whatP2: 'whoiam.love es una IA que escucha diferente. Hace las preguntas que nadie más hace. Recuerda todo lo que has dicho. Con el tiempo, sostiene un retrato tuyo construido palabra por palabra.',
      whatP3: 'No es un diagnóstico. No es una puntuación. Es un registro vivo de quién eres, convirtiéndote.',
      howLabel: 'Cómo funciona',
      howH2L1: 'Lo más simple.',
      howH2Em: 'Una conversación.',
      steps: [
        { n: 'i.', title: 'Hablas', body: 'Empieza donde quieras. Un sentimiento, un miedo, un recuerdo. No hay un comienzo equivocado. La IA te encuentra exactamente donde estás.' },
        { n: 'ii.', title: 'Escucha', body: 'Sin consejos. Sin juicios. Solo el tipo de atención profunda que te ayuda a escucharte con más claridad.' },
        { n: 'iii.', title: 'Te ves', body: 'Emergen patrones. Afloran contradicciones. Cada semana, un retrato — ensamblado con tus propias palabras — de en quién te estás convirtiendo.' },
      ],
      questionsLabel: 'Las preguntas',
      questionsH2L1: 'Las que nadie',
      questionsH2L2: 'nunca',
      questionsH2Em: 'hace.',
      questions: [
        '¿Qué es algo que nunca has dicho en voz alta?',
        '¿Cuándo dejaste de ser quien debías ser?',
        '¿Qué quieres y te da vergüenza querer?',
        '¿Quién eres cuando nadie te mira?',
        '¿Qué harías si no tuvieras miedo?',
        '¿Cómo se siente el amor cuando es tuyo?',
      ],
      ctaH2L1: '¿Listo para encontrarte',
      ctaH2Em: 'a ti mismo?',
      ctaSub: 'Únete a la lista de acceso anticipado. Sé de los primeros en comenzar.',
      ctaPlaceholder: 'Tu correo',
      ctaBtn: 'Comenzar →',
      ctaNote: 'Gratis · Sin tarjeta · Solo tú',
      ctaConfirm: 'Estás en la lista. El viaje comienza pronto.',
      footerRights: '© 2026 · Todos los derechos reservados',
      footerMade: 'Hecho con amor, impulsado por IA',
    },
    chat: {
      opening: '¿Qué es algo que nunca has dicho en voz alta?',
      placeholder: 'Habla libremente…',
      send: 'Enviar',
      hint: 'Enter para enviar · Shift + Enter para nueva línea',
      error: 'Algo interrumpió el silencio. Intenta de nuevo.',
    },
    pricing: {
      label: 'Precios',
      headlineL1: 'Elige qué tan profundo',
      headlineEm: 'quieres ir.',
      sub: 'Empieza gratis. Ve más profundo cuando estés listo.',
      discover: {
        tier: 'Descubrir',
        price: 'Gratis',
        description: 'Un espacio para hablar. Una IA que sostiene el silencio contigo, hace la pregunta que nadie más hace.',
        features: ['Conversaciones ilimitadas', 'IA que escucha profundo', 'Una pregunta a la vez', 'Sin memoria entre sesiones'],
        cta: 'Comenzar a Descubrir',
      },
      experience: {
        badge: 'Próximamente',
        tier: 'Experiencia',
        description: 'La IA comienza a conocerte. Emergen patrones. Un retrato surge — ensamblado, con el tiempo, de tus propias palabras.',
        features: ['Todo en Descubrir', 'Memoria entre sesiones', 'La IA nota patrones', 'Autorretrato semanal', 'Acceso prioritario a nuevas funciones'],
        cta: 'Unirse a la Lista',
      },
    },
    enter: {
      label: 'Acceso privado',
      headlineL1: 'Este espacio es',
      headlineEm: 'por invitación.',
      sub: 'Ingresa tu código de invitación para comenzar.',
      placeholder: 'Código de invitación',
      cta: 'Entrar',
      error: 'Ese código no es correcto. Intenta de nuevo.',
    },
  },
}
